//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervent.Web.DataLayerCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar_AE {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar_AE() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervent.Web.DataLayerCore.Properties.ar-AE", typeof(ar_AE).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما من أحد إلا ويحب أن يحظى بمزيد من الدعم. سيسعدك العمل مع طاقمنا المتفاني من أخصائيي الرعاية الصحية.
        /// </summary>
        internal static string L1343 {
            get {
                return ResourceManager.GetString("L1343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لن تحظى فقط بصحة أفضل – يمكنك الفوز بجوائز قيمة عن الأنشطة التي تتمها.
        /// </summary>
        internal static string L1344 {
            get {
                return ResourceManager.GetString("L1344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواردنا متاحة دائمًا من أجلك – على حاسوبك، وجهازك اللوحي، وهاتفك الذكي.
        /// </summary>
        internal static string L1345 {
            get {
                return ResourceManager.GetString("L1345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ الآن – فاليوم مناسب جدًا للعمل على تحسين صحتك... ما الذي يمنعك؟.
        /// </summary>
        internal static string L1346 {
            get {
                return ResourceManager.GetString("L1346", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصفحة الرئيسية.
        /// </summary>
        internal static string L1347 {
            get {
                return ResourceManager.GetString("L1347", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموظف.
        /// </summary>
        internal static string L1361 {
            get {
                return ResourceManager.GetString("L1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد ({0}).
        /// </summary>
        internal static string L1362 {
            get {
                return ResourceManager.GetString("L1362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استنادًا إلى إجاباتك على تقييمنا الصحي، سنقدم لك استشارة متخصصة – خاصة بك وحدك..
        /// </summary>
        internal static string L1378 {
            get {
                return ResourceManager.GetString("L1378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد كتابة كلمة المرور.
        /// </summary>
        internal static string L1628 {
            get {
                return ResourceManager.GetString("L1628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة مرورك. يرجى تسجيل الدخول بعنوان بريدك الإلكتروني وكلمة المرور الجديدة..
        /// </summary>
        internal static string L1630 {
            get {
                return ResourceManager.GetString("L1630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بريدك الإلكتروني.
        /// </summary>
        internal static string L1632 {
            get {
                return ResourceManager.GetString("L1632", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعذر إعادة تعيين كلمة المرور.
        /// </summary>
        internal static string L1633 {
            get {
                return ResourceManager.GetString("L1633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} مطلوب.
        /// </summary>
        internal static string L1895 {
            get {
                return ResourceManager.GetString("L1895", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديد نوع الموظف.
        /// </summary>
        internal static string L1896 {
            get {
                return ResourceManager.GetString("L1896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موظف.
        /// </summary>
        internal static string L1897 {
            get {
                return ResourceManager.GetString("L1897", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزوج/الزوجة.
        /// </summary>
        internal static string L1899 {
            get {
                return ResourceManager.GetString("L1899", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الموظف مطلوب.
        /// </summary>
        internal static string L1900 {
            get {
                return ResourceManager.GetString("L1900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد مطلوب..
        /// </summary>
        internal static string L1903 {
            get {
                return ResourceManager.GetString("L1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد مطلوب..
        /// </summary>
        internal static string L19031 {
            get {
                return ResourceManager.GetString("L19031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حوافز INTERVENT.
        /// </summary>
        internal static string L1919 {
            get {
                return ResourceManager.GetString("L1919", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة الإنجليزية.
        /// </summary>
        internal static string L1921 {
            get {
                return ResourceManager.GetString("L1921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اللغة الإسبانية.
        /// </summary>
        internal static string L1922 {
            get {
                return ResourceManager.GetString("L1922", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ألا تقل كلمات المرور عن 8 أحرف وأن تحتوي على الأقل على حرف واحد من الأحرف الكبيرة والصغيرة ورقم واحد..
        /// </summary>
        internal static string L1929 {
            get {
                return ResourceManager.GetString("L1929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في التسجيل.
        /// </summary>
        internal static string L1931 {
            get {
                return ResourceManager.GetString("L1931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء حسابك بنجاح وأصبح جاهزًا للاستخدام..
        /// </summary>
        internal static string L1932 {
            get {
                return ResourceManager.GetString("L1932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال معلومات المستخدم الرئيسي لاستكمال التسجيل..
        /// </summary>
        internal static string L1933 {
            get {
                return ResourceManager.GetString("L1933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل غير موجود. يرجى التحقق من {0} المدخل..
        /// </summary>
        internal static string L1967 {
            get {
                return ResourceManager.GetString("L1967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم نتمكن من العثور على تطابق تام. يرجى التحقق من المعلومات المدخلة..
        /// </summary>
        internal static string L1968 {
            get {
                return ResourceManager.GetString("L1968", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحساب موجود بالفعل. يرجى تسجيل الدخول إلى الحساب الموجود..
        /// </summary>
        internal static string L1969 {
            get {
                return ResourceManager.GetString("L1969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء معالجة الطلب.
        /// </summary>
        internal static string L1970 {
            get {
                return ResourceManager.GetString("L1970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن يكون العمر أكبر من 18 عامًا.
        /// </summary>
        internal static string L1986 {
            get {
                return ResourceManager.GetString("L1986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التزويد بعنوان بريد إلكتروني صالح. يجب أن يقدم الزوج/الزوجة عنوان بريد إلكتروني مستقلًا وفريدًا..
        /// </summary>
        internal static string L1988 {
            get {
                return ResourceManager.GetString("L1988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يبدو أنك اخترت نوع الموظف الخطأ..
        /// </summary>
        internal static string L1989 {
            get {
                return ResourceManager.GetString("L1989", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفون – أدخل اسمك الأول واسم العائلة، وتاريخ الميلاد و  {2}.&lt;br&gt;&lt;br&gt;الأزواج/الزوجات (من غير العاملين لدى {0}) – أدخل/أدخلي اسمك الأول واسم العائلة، وتاريخ الميلاد و  {2} الموظف {1}.&lt;br&gt;&lt;br&gt;الأزواج/الزوجات الموظفان كلاهما في {0}) – على كل موظف إدخال الاسم الأول، واسم العائلة، وتاريخ الميلاد. أدخل {2} للشخص الذي يعتبر العضو الرئيسي في البرنامج الطبي..
        /// </summary>
        internal static string L238 {
            get {
                return ResourceManager.GetString("L238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابك غير فعال. يرجى تأكيد حسابك أو إعادة إرسال بريد التأكيد الإلكتروني عن طريق النقر فوق الرابط التالي..
        /// </summary>
        internal static string L2396 {
            get {
                return ResourceManager.GetString("L2396", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة إرسال بريد التأكيد الإلكتروني إلى.
        /// </summary>
        internal static string L2397 {
            get {
                return ResourceManager.GetString("L2397", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى مراجعة تفاصيل البريد الإلكتروني لتفعيل حسابك..
        /// </summary>
        internal static string L2398 {
            get {
                return ResourceManager.GetString("L2398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طفل.
        /// </summary>
        internal static string L2399 {
            get {
                return ResourceManager.GetString("L2399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معال بالغ.
        /// </summary>
        internal static string L2400 {
            get {
                return ResourceManager.GetString("L2400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاتصال بنا.
        /// </summary>
        internal static string L2435 {
            get {
                return ResourceManager.GetString("L2435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصوصية.
        /// </summary>
        internal static string L2436 {
            get {
                return ResourceManager.GetString("L2436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حسابي.
        /// </summary>
        internal static string L2437 {
            get {
                return ResourceManager.GetString("L2437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من رقم هويتك الفريد. رقم هويتك الفريد هو الرقم الذي يجمع بين آخر أربعة أرقام من رقم ضمانك الاجتماعي وتاريخ ميلادك شاملًا الأصفار. على سبيل المثال إذا كان رقم ضمانك الاجتماعي xxx-xx-1234 وتاريخ ميلاد 03/05/1970، فأدخل 123403051970..
        /// </summary>
        internal static string L2466 {
            get {
                return ResourceManager.GetString("L2466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة كتابة عنوان البريد الإلكتروني.
        /// </summary>
        internal static string L2468 {
            get {
                return ResourceManager.GetString("L2468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير مطابق.
        /// </summary>
        internal static string L2469 {
            get {
                return ResourceManager.GetString("L2469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطعام الذي تتناوله، والضغوط التي تشعر بها، والأنشطة التي تقوم بها، تؤثر جميعًا في صحتك. وبإمكانك الآن معرفة كيف يحدث ذلك من خلال إتمام تقييمنا الصحي..
        /// </summary>
        internal static string L2470 {
            get {
                return ResourceManager.GetString("L2470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        internal static string L254 {
            get {
                return ResourceManager.GetString("L254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الإلكتروني هذا مستخدم بالفعل. يرجى التزويد بعنوان بريد إلكتروني فريد..
        /// </summary>
        internal static string L2560 {
            get {
                return ResourceManager.GetString("L2560", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يحق لك إنشاء حساب. للحصول على مزيد من المساعدة يرجى الاتصال بخدمة العملاء على ‎1-855-494-1093..
        /// </summary>
        internal static string L2569 {
            get {
                return ResourceManager.GetString("L2569", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية رابط إعادة التعيين بعد ساعة واحدة أو أنه سبق استخدامه بالفعل. يرجى النقر فوق زر &quot;إعادة تعيين كلمة المرور&quot;، وستتلقى بريدًا إلكترونيًا يحتوي على رابط جديد..
        /// </summary>
        internal static string L2577 {
            get {
                return ResourceManager.GetString("L2577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير مطابقة.
        /// </summary>
        internal static string L263 {
            get {
                return ResourceManager.GetString("L263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحلتك إلى الصحة المثلى والرفاهة تبدأ هنا... والآن.
        /// </summary>
        internal static string L2693 {
            get {
                return ResourceManager.GetString("L2693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة نمط حياة الأمهات.
        /// </summary>
        internal static string L2710 {
            get {
                return ResourceManager.GetString("L2710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        internal static string L3070 {
            get {
                return ResourceManager.GetString("L3070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حققت برامجنا نجاحًا مع أكثر من 2 مليون شخص في جميع أنحاء العالم..
        /// </summary>
        internal static string L3111 {
            get {
                return ResourceManager.GetString("L3111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احصل على جوائز لقاء جهودك.
        /// </summary>
        internal static string L3112 {
            get {
                return ResourceManager.GetString("L3112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التدريب الحي.
        /// </summary>
        internal static string L3113 {
            get {
                return ResourceManager.GetString("L3113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة العافية والحالات الطبية المزمنة.
        /// </summary>
        internal static string L3114 {
            get {
                return ResourceManager.GetString("L3114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرفاهة – التعامل مع الضغوط – القدرة على الصمود.
        /// </summary>
        internal static string L3115 {
            get {
                return ResourceManager.GetString("L3115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التعامل مع الإعاقة – العودة إلى العمل.
        /// </summary>
        internal static string L3116 {
            get {
                return ResourceManager.GetString("L3116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طالع واحدة من قصص النجاح العديدة.
        /// </summary>
        internal static string L3117 {
            get {
                return ResourceManager.GetString("L3117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكنك الفوز بجوائز قيمة من INTERVENT. ستقدم INTERVENT نقاطًا مقابل استكمال أنشطة البرامج المختلفة، كما تجري سحوبات شهرية، وفصلية، ونصف سنوية، وسنوية لاختيار الفائزين. وكلما زاد النقاط التي تحوزها، زادت فرص فوزك.  المشاركون المسجلون في برامج التدريب الصحي والمشاركون فيها بفاعلية فقط هم الذين يحق لهم دخول السحوبات..
        /// </summary>
        internal static string L3118 {
            get {
                return ResourceManager.GetString("L3118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راجع إعلانات الفائزين واقرأ القصص التي تتحدث عن دور العمل مع مدربي INTERVENT الصحيين في مساعدة المشاركين على المضي قدمًا على طريق الوصول إلى الصحة المثلى..
        /// </summary>
        internal static string L3119 {
            get {
                return ResourceManager.GetString("L3119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وهذا التقييم الصحي مجاني، وسري، ويتم عبر الإنترنت، للنظر في عادات نمط حياتك وتاريخك الصحي، لتحديد مدى الصحة التي تتمتع بها، وما إذا كنت معرضًا لمخاطر الأمراض أو الاعتلالات المزمنة، أو مجالات التعامل معها بصورة أفضل. ولن يستغرق إتمامه سوى 15 دقيقة تقريبًا..
        /// </summary>
        internal static string L3120 {
            get {
                return ResourceManager.GetString("L3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبعد إتمام التقييم الصحي، ستتلقى على الفور تقريرًا شخصيًا عن العافية، ومجموعة غزيرة من المعلومات المفيدة المخصصة لك بصفة شخصية. يجب عليك إتمام التقييم الصحي قبل التسجيل في أحد برامج التدريب على نمط الحياة الصحية. وإذا كانت لديك أي استفسارات فأرسلها إلينا بالبريد الإلكتروني أو اتصل بنا..
        /// </summary>
        internal static string L3121 {
            get {
                return ResourceManager.GetString("L3121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فمدربونا الصحيون يكرسون أنفسهم لرعايتك ومتاحون دائمًا لك في أي وقت يناسبك. وقد سبق لهم العمل مع الآلاف من المشاركين مثلك. وسيستمع مدربونا لاحتياجاتك، وتفضيلاتك، وظروفك، وسيساعدونك على وضع خطة شخصية تناسبك. وسيتابع معك مدربك مدى تحقيقك للأهداف التي وضعتها لنفسك، وسيساندك في كل خطوة تخطوها على طريق الوصول إلى صحة أفضل..
        /// </summary>
        internal static string L3122 {
            get {
                return ResourceManager.GetString("L3122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عليك إتمام التقييم الصحي قبل التسجيل في أحد برامج التدريب على نمط الحياة الصحية..
        /// </summary>
        internal static string L3123 {
            get {
                return ResourceManager.GetString("L3123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تشمل برامجنا الهاتفية للتدريب الصحي:.
        /// </summary>
        internal static string L3124 {
            get {
                return ResourceManager.GetString("L3124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة نمط الحياة – الأكل بطريقة صحية، الحفاظ على النشاط البدني، التعامل مع الضغوط، عدم التدخين واتباع خطتك العلاجية وإرشادات الرعاية الوقائية – هي أساس التمتع بالصحة المثلى والرفاه.
        /// </summary>
        internal static string L3125 {
            get {
                return ResourceManager.GetString("L3125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا كنت تعاني من حالة مزمنة، فيمكن لبرنامجنا الهاتفي للتدريب الصحي أن يساعدك على تنفيذ خطة العلاج الموصى بها من قبل الطبيب أو مقدم الرعاية الصحية وعيش حياة أفضل مع حالتك..
        /// </summary>
        internal static string L3126 {
            get {
                return ResourceManager.GetString("L3126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا كانت تتمتع بصحة عامة جيدة، وتود أن تبقى كذلك، فسيركز برنامج تدريبك على تعزيز الصحة والعافية، وإدارة عوامل الخطر، والوقاية من الأمراض..
        /// </summary>
        internal static string L3127 {
            get {
                return ResourceManager.GetString("L3127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وجميع برامج إدارة العافية والحالات الطبية المزمنة مخصصة فرديًا لتلبية احتياجاتك وتفضيلاتك. وسوف تخطو خطوات صغيرة منتظمة تمكنك من إحداث فارق كبير في حالتك الصحية ونمط حياتك..
        /// </summary>
        internal static string L3128 {
            get {
                return ResourceManager.GetString("L3128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عندما التحقت ببرنامج التدريب، علمت أن بإمكاني التقليل من مخاطر تحول مقدمات السكري لدي إلى النوع الثاني من داء السكري عن طريق فقد خمسة إلى 10 في المائة من وزني وزيادة نشاطي البدني. وبمساعدة مدربي الصحي، فقدت الآن 12 كيلو جرامًا (حوالي 26 رطلًا)، ويسعدني أن أقول إنني لم أعد أعاني من مقدمات السكري. كما أصبحت قيمة الكوليسترول لدي في النطاق الطبيعي. أشعر بسعادة كبيرة. لم أكن لأحقق هذه التغييرات لولا الدعم الذي قدمه مدربي الصحي. لذا، فإنني أمنح برنامج التدريب تقديرًا ممتازًا، وأوصي به غيري ممن هم بحاجة إلى التعام [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3129 {
            get {
                return ResourceManager.GetString("L3129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ليست كل الضغوط سيئة، ولكن حتى الضغوط الجيدة - كضغوط السعي للترقي في العمل - يمكن أن تكون مجهدة للأعصاب وتؤثر سلبًا على صحتك. وتتناول برامجنا المعنية بالتعامل مع الضغوط مهارات الاسترخاء والتأقلم وغيرها من السلوكيات المهمة لتعزيز القدرة على الصمود في وجه الأوقات الصعبة. وتشمل موضوعات البرامج: إدارة الوقت، تحقيق التوازن بين العمل والحياة، القيم، أنماط التواصل، بناء الثقة، الدعم الاجتماعي، التركيز الذهني الكامل، التفكير بطريقة مختلفة، حل المشكلات، التعامل مع الاكتئاب، ومنع حدوث الانتكاسات. وبوسع الكل تقريبًا ال [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3130 {
            get {
                return ResourceManager.GetString("L3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وإذا كان المشاركون يعانون من مشكلات تتجاوز نطاق برنامج التدريب، فسنحيلهم إلى جهات أخرى ملائمة للصحة النفسية..
        /// </summary>
        internal static string L3131 {
            get {
                return ResourceManager.GetString("L3131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جميعنا يتعرض للضغوط في وقت من الأوقات – أليس كذلك؟ حسنًا، بالنسبة لي، كان السبب وراء الضغوط التي أعانيها هو فقدي لزوجي بعد زواج دام 25 عامًا. وكنت قد أمضيت عدة أشهر في برنامج التدريب على الرفاهة عندما توفي فجأة. ومن حسن الحظ، أنني استطعت أن أطبق العديد من مبادئ الصمود في مواجهة الأزمات التي تعلمتها من مدربي للتعامل مع حزني وما صاحبه من ضغوط. وكان بإمكاني طلب المساعدة من الآخرين وقبولها منهم، والبحث عمن يستمع إلي. وشاركت أيضًا في بعض الأنشطة التطوعية بمجتمعي، الأمر الذي ساعدني على تركيز اهتمامي على الآخرين ب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3132 {
            get {
                return ResourceManager.GetString("L3132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تتوقف إدارة نمط الحياة عند تعرضك لحادث، أو دخول المستشفى، أو الإصابة بمرض خطير، أو أي انتكاسة أخرى. بل، في الواقع، من شأن التدرب على عادات أكثر صحية خلال فترات تعطل الحياة الطبيعية تلك أن يساعدك على العودة إلى جدولك المعتاد وإلى عملك، وإلى الأنشطة التي تحقق لك السعادة، في أقرب وقت ممكن عمليًا..
        /// </summary>
        internal static string L3133 {
            get {
                return ResourceManager.GetString("L3133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وسنساعدك على أن تكون مدافعًا عن صحتك الشخصية للتعامل مع الإعاقات قصيرة أو طويلة الأجل. وسيساعدك مدربك على نمط الحياة الصحي على الوصول إلى طائفة كاملة من موارد التعافي، بما في ذلك إعادة التأهيل والعلاج الطبيعي للمرضى الخارجيين. وفي الوقت المناسب، يمكنك الانتقال إلى برنامجنا الخاص بالإدارة الشاملة لنمط الحياة للحصول على دعم مستمر..
        /// </summary>
        internal static string L3134 {
            get {
                return ResourceManager.GetString("L3134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد الجراحة التي أجريتها في الظهر، كنت قلقًا بشأن عودتي للعمل، لذا التحقت ببرنامج التدريب أثناء قيامي بإعادة التأهيل البدني. وخلال هذا الوقت، ساعدني مدربي على الوصول إلى مختلف خدمات التعافي اللازمة لعودتي للعمل. وانصب تركيزنا أيضًا على فقد الوزن وضبط ضغط الدم؛ وهما المشكلتان اللتان كنت أعاني منهما قبل الجراحة. وبعد أربعة أسابيع فقط، تمكنت من العودة إلى أداء مهام محدودة، وبعد ثلاثة أشهر، عدت لممارسة مهامي كاملة. والآن فقدت تسعة كيلو جرامات (حوالي 20 رطلًا)، وتحسن ضغط دمي، وأحافظ على نشاطي. وقد انخفضت مخاطر ت [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3135 {
            get {
                return ResourceManager.GetString("L3135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البرنامج للتدريب على نمط الحياة الصحية مخصص للنساء الحوامل أو اللاتي يخططن للحمل في المستقبل القريب. وتركز الموضوعات المعنية بفترة ما قبل الولادة بصفة أساسية على العافية العامة (التغذية، النشاط البدني، التعامل مع الضغوط) للمساعدة على  المرور بحمل صحي. وتتناول الموضوعات المعنية بفترة ما بعد الولادة استعادة القوام، وفقدان الوزن المكتسب أثناء الحمل، والتكيف مع الحياة في ظل وجود مولود جديد. كما تتوافر سلسلة تعليمية خاصة موجهة للنساء اللاتي يفكرن في الرضاعة الطبيعية لمولودهن..
        /// </summary>
        internal static string L3136 {
            get {
                return ResourceManager.GetString("L3136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ومن شأن المشاركة في برنامج التدريب على نمط الحياة الصحية للأمهات أن يحسن من احتمالات اجتياز الحمل بنجاح، ووضع مولود يتمتع بصحة جيدة. أما المسائل الإكلينيكية فتحال دائمًا إلى الأطباء الشخصيين للسيدة أو مقدمي الرعاية الصحية. كما تشجع النساء أيضًا على الاستفادة من الموارد الخاصة برعاية ما قبل الولادة، ورعاية الأم والمولود الجديد، التي يقدمها مقدمو الرعاية الصحية في الأماكن التي سيلدن بها..
        /// </summary>
        internal static string L3137 {
            get {
                return ResourceManager.GetString("L3137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بمجرد أن عرفت بحملي، التحقت ببرنامج التدريب على نمط الحياة الصحي للأمهات. فلم يكن لدي أدنى علم عن معنى أن يكون لدي طفل، وخصوصًا الأمور المتعلقة بالمواعيد والفحوص الطبية خلال فترة ما قبل الولادة. وقد أجاب مدربي على جميع أسئلتي وساعدني على معرفة ما ينبغي أن أتوقعه في كل شهر طوال رحلة الحمل. وبعد أن وضعت ابنتي، واصلت برنامج التدريب لكي أفقد الكيلو جرامات الخمسة (حوالي 11 رطلًا) التي اكتسبتها أثناء الحمل والحصول على قوام أفضل. وبعد ثلاثة أشهر فقط، استعدت الوزن الذي كنت عليه قبل الحمل. وأنا في تطلع دائمًا لجلسات [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3138 {
            get {
                return ResourceManager.GetString("L3138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بوابة تجريبية لعملاء MAXIS GBN.
        /// </summary>
        internal static string L3139 {
            get {
                return ResourceManager.GetString("L3139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string L3140 {
            get {
                return ResourceManager.GetString("L3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقق الأهداف المهمة لديك.
        /// </summary>
        internal static string L3141 {
            get {
                return ResourceManager.GetString("L3141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        internal static string L3149 {
            get {
                return ResourceManager.GetString("L3149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راسلنا على البريد الإلكتروني.
        /// </summary>
        internal static string L3150 {
            get {
                return ResourceManager.GetString("L3150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية-AE.
        /// </summary>
        internal static string L3159 {
            get {
                return ResourceManager.GetString("L3159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVENT.
        /// </summary>
        internal static string L424 {
            get {
                return ResourceManager.GetString("L424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحة أفضل مدى الحياة Better Health for Life™‎.
        /// </summary>
        internal static string L425 {
            get {
                return ResourceManager.GetString("L425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string L426 {
            get {
                return ResourceManager.GetString("L426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حسابي.
        /// </summary>
        internal static string L431 {
            get {
                return ResourceManager.GetString("L431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول مطلوب..
        /// </summary>
        internal static string L432 {
            get {
                return ResourceManager.GetString("L432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة مطلوب..
        /// </summary>
        internal static string L433 {
            get {
                return ResourceManager.GetString("L433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بريدك الإلكتروني مطلوب..
        /// </summary>
        internal static string L434 {
            get {
                return ResourceManager.GetString("L434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير مطابقة.
        /// </summary>
        internal static string L438 {
            get {
                return ResourceManager.GetString("L438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الخدمة.
        /// </summary>
        internal static string L440 {
            get {
                return ResourceManager.GetString("L440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوافق على.
        /// </summary>
        internal static string L441 {
            get {
                return ResourceManager.GetString("L441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لتتمكن من الاستفادة من خدماتنا، يجب عليك الموافقة على اتفاقية المشاركة والخدمة وسياسة الخصوصية لشركة INTERVENT..
        /// </summary>
        internal static string L442 {
            get {
                return ResourceManager.GetString("L442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string L443 {
            get {
                return ResourceManager.GetString("L443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحصول على تقرير شخصي عن العافية.
        /// </summary>
        internal static string L446 {
            get {
                return ResourceManager.GetString("L446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقيق الأهداف المهمة لديك.
        /// </summary>
        internal static string L451 {
            get {
                return ResourceManager.GetString("L451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التواصل مع مدرب صحي.
        /// </summary>
        internal static string L453 {
            get {
                return ResourceManager.GetString("L453", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصول إلى INTERVENT أثناء تنقلك.
        /// </summary>
        internal static string L459 {
            get {
                return ResourceManager.GetString("L459", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تأكيد حسابك الجديد! استخدم عنوان بريدك الإلكتروني وكلمة المرور لتسجيل الدخول..
        /// </summary>
        internal static string L462 {
            get {
                return ResourceManager.GetString("L462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى ‏‏إدخال عنوان بريدك الإلكتروني.
        /// </summary>
        internal static string L463 {
            get {
                return ResourceManager.GetString("L463", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال كلمة المرور.
        /// </summary>
        internal static string L464 {
            get {
                return ResourceManager.GetString("L464", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        internal static string L465 {
            get {
                return ResourceManager.GetString("L465", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string L466 {
            get {
                return ResourceManager.GetString("L466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} غير موجود بنظامنا. يرجى الاتصال على ‎1-855-494-1093 للحصول على مزيد من المساعدة..
        /// </summary>
        internal static string L467 {
            get {
                return ResourceManager.GetString("L467", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى مراجعة بريدك الإلكتروني للاطلاع على تعليمات إعادة تعيين كلمة المرور..
        /// </summary>
        internal static string L468 {
            get {
                return ResourceManager.GetString("L468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنرسل لك بالبريد الإلكتروني تعليمات لكيفية إعادة تعيين كلمة مرورك..
        /// </summary>
        internal static string L469 {
            get {
                return ResourceManager.GetString("L469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        internal static string L470 {
            get {
                return ResourceManager.GetString("L470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الحساب.
        /// </summary>
        internal static string L474 {
            get {
                return ResourceManager.GetString("L474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال بريد إلكتروني لتأكيد الحساب على.
        /// </summary>
        internal static string L475 {
            get {
                return ResourceManager.GetString("L475", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر فوق الرابط الوارد بالرسالة للمصادقة واستكمال عملية إنشاء الحساب..
        /// </summary>
        internal static string L476 {
            get {
                return ResourceManager.GetString("L476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا لم تجد الرسالة في صندوق الوارد، فحاول البحث عنها في مجلد الرسائل المزعجة..
        /// </summary>
        internal static string L477 {
            get {
                return ResourceManager.GetString("L477", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موافق.
        /// </summary>
        internal static string L478 {
            get {
                return ResourceManager.GetString("L478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء معالجة طلب مصادقة حسابك..
        /// </summary>
        internal static string L479 {
            get {
                return ResourceManager.GetString("L479", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم الصحي.
        /// </summary>
        internal static string L535 {
            get {
                return ResourceManager.GetString("L535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        internal static string L938 {
            get {
                return ResourceManager.GetString("L938", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم العائلة.
        /// </summary>
        internal static string L939 {
            get {
                return ResourceManager.GetString("L939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string L986 {
            get {
                return ResourceManager.GetString("L986", resourceCulture);
            }
        }
    }
}
