//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Intervent.Web.DataLayerCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Intervent.Web.DataLayerCore.Properties.ar", typeof(ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن للجميع الاستفادة من الدعم الإضافي، ستحب العمل مع أحد اختصاصيي الصحة المحترفين لدينا.
        /// </summary>
        internal static string L1343 {
            get {
                return ResourceManager.GetString("L1343", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصحة الأفضل ليست المكافاة الوحيدة - فز بجوائز قيمة للأنشطة التي تقوم بإكمالها.
        /// </summary>
        internal static string L1344 {
            get {
                return ResourceManager.GetString("L1344", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواردنا دائما متوفرون من أجلك - على كمبيوترك الشخصي واللوحي والهاتف الذكي.
        /// </summary>
        internal static string L1345 {
            get {
                return ResourceManager.GetString("L1345", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أبدا الآن-اليوم هو يوم جيد لتحسين صحتك... ما الذي يوقفك ؟.
        /// </summary>
        internal static string L1346 {
            get {
                return ResourceManager.GetString("L1346", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرئيسية.
        /// </summary>
        internal static string L1347 {
            get {
                return ResourceManager.GetString("L1347", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الموظف.
        /// </summary>
        internal static string L1361 {
            get {
                return ResourceManager.GetString("L1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد ({0}).
        /// </summary>
        internal static string L1362 {
            get {
                return ResourceManager.GetString("L1362", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استنادا إلى استجاباتك لتقييمنا الصحي، سنقدم لك مشورة الخبراء – المخصصة من أجلك..
        /// </summary>
        internal static string L1378 {
            get {
                return ResourceManager.GetString("L1378", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد كتابة كلمة المرور.
        /// </summary>
        internal static string L1628 {
            get {
                return ResourceManager.GetString("L1628", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور الخاصة بك، يرجى تسجيل الدخول باستخدام البريد الكتروني وكلمة المرور الجديدة..
        /// </summary>
        internal static string L1630 {
            get {
                return ResourceManager.GetString("L1630", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بريدك الإلكتروني.
        /// </summary>
        internal static string L1632 {
            get {
                return ResourceManager.GetString("L1632", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فشل في إعادة ضبط كلمة المرور.
        /// </summary>
        internal static string L1633 {
            get {
                return ResourceManager.GetString("L1633", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} مطلوب.
        /// </summary>
        internal static string L1895 {
            get {
                return ResourceManager.GetString("L1895", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختر نوع الشخص.
        /// </summary>
        internal static string L1896 {
            get {
                return ResourceManager.GetString("L1896", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريك.
        /// </summary>
        internal static string L1897 {
            get {
                return ResourceManager.GetString("L1897", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الزوج/الزوجة.
        /// </summary>
        internal static string L1899 {
            get {
                return ResourceManager.GetString("L1899", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الشخص مطلوب.
        /// </summary>
        internal static string L1900 {
            get {
                return ResourceManager.GetString("L1900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد مطلوب.
        /// </summary>
        internal static string L1903 {
            get {
                return ResourceManager.GetString("L1903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد مطلوب.
        /// </summary>
        internal static string L19031 {
            get {
                return ResourceManager.GetString("L19031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحوافز الخاصة بـ INTERVENT.
        /// </summary>
        internal static string L1919 {
            get {
                return ResourceManager.GetString("L1919", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإنجليزية.
        /// </summary>
        internal static string L1921 {
            get {
                return ResourceManager.GetString("L1921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسبانية.
        /// </summary>
        internal static string L1922 {
            get {
                return ResourceManager.GetString("L1922", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن تكون كلمات المرور من 8 أحرف على أن تكون حرف واحد على الأقل من الأحرف الكبيرة والصغيرة وواحد من الأرقام  ..
        /// </summary>
        internal static string L1929 {
            get {
                return ResourceManager.GetString("L1929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطأ في التسجيل.
        /// </summary>
        internal static string L1931 {
            get {
                return ResourceManager.GetString("L1931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قد تم إنشاء حسابك بنجاح وهو جاهز للاستخدام..
        /// </summary>
        internal static string L1932 {
            get {
                return ResourceManager.GetString("L1932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال معلومات المستخدم الأساسي لمتابعة التسجيل..
        /// </summary>
        internal static string L1933 {
            get {
                return ResourceManager.GetString("L1933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السجل غير موجود. يرجى التحقق من {0} الذي تم إدخاله..
        /// </summary>
        internal static string L1967 {
            get {
                return ResourceManager.GetString("L1967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم نتمكن من العثور علي تطابق تام. الرجاء التحقق من المعلومات التي تم إدخالها..
        /// </summary>
        internal static string L1968 {
            get {
                return ResourceManager.GetString("L1968", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد الحساب مسبقا، يرجى تسجيل الدخول إلى حسابك الحالي..
        /// </summary>
        internal static string L1969 {
            get {
                return ResourceManager.GetString("L1969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ أثناء معالجة الطلب.
        /// </summary>
        internal static string L1970 {
            get {
                return ResourceManager.GetString("L1970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون العمر أكبر من 18.
        /// </summary>
        internal static string L1986 {
            get {
                return ResourceManager.GetString("L1986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى توفير عنوان بريد إلكتروني ساري، يجب على الزوج/الزوجة تقديم عنوان بريد إلكتروني منفصل وخاص..
        /// </summary>
        internal static string L1988 {
            get {
                return ResourceManager.GetString("L1988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يبدو أنك قمت بتحديد نوع الموظف الخطأ..
        /// </summary>
        internal static string L1989 {
            get {
                return ResourceManager.GetString("L1989", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شريك - أدخل اسمك الأول والأخير وتاريخ الميلاد، و{2}.&lt;br&gt;&lt;br&gt;الزوج/الزوجة (والذي/والتي لا يعمل/تعمل لدى {0}) – أدخل اسمك الأول والأخير وتاريخ الميلاد، و {2} من {1} شريك.&lt;br&gt;&lt;br&gt; الزوج/الزوجة (واللذان هما الشريكان ل {0}) – ويجب على كل من الشركاء إدخال اسمه/اسمها الأول والأخير وتاريخ الميلاد.  أدخل {2} من الأشخاص الذي هو العضو الأساسي للخطة الطبية..
        /// </summary>
        internal static string L238 {
            get {
                return ResourceManager.GetString("L238", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابك غير فعال، يرجى تأكيد حسابك أو إعادة إرسال بريد التأكيد الإلكتروني عن طريق النقر على الرابط أدناه..
        /// </summary>
        internal static string L2396 {
            get {
                return ResourceManager.GetString("L2396", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد إرسال بريد التأكيد الإكتروني إلى.
        /// </summary>
        internal static string L2397 {
            get {
                return ResourceManager.GetString("L2397", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من تفاصيل البريد الإلكتروني لتفعيل حسابك..
        /// </summary>
        internal static string L2398 {
            get {
                return ResourceManager.GetString("L2398", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طفل.
        /// </summary>
        internal static string L2399 {
            get {
                return ResourceManager.GetString("L2399", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملتحق بالغ.
        /// </summary>
        internal static string L2400 {
            get {
                return ResourceManager.GetString("L2400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصل بنا.
        /// </summary>
        internal static string L2435 {
            get {
                return ResourceManager.GetString("L2435", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخصوصية.
        /// </summary>
        internal static string L2436 {
            get {
                return ResourceManager.GetString("L2436", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشئ حسابي.
        /// </summary>
        internal static string L2437 {
            get {
                return ResourceManager.GetString("L2437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من رقم الهوية الفريد الخاص بك، فرقم الهوية الفريد الخاص بك عبارة عن مزيج من آخر أربعة أرقام من رقم التأمين الاجتماعي (SSN) الخاص بك وتاريخ ميلادك شاملا الأصفار. علي سبيل المثال ، إذا كان رقم SSN الخاص بك هو xxx-xx-1234 وتاريخ الميلاد هو 03/05/1970, يجب عليك أن تدخل 123403051970..
        /// </summary>
        internal static string L2466 {
            get {
                return ResourceManager.GetString("L2466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد كتابة عنوان البريد الإلكتروني.
        /// </summary>
        internal static string L2468 {
            get {
                return ResourceManager.GetString("L2468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير متطابق.
        /// </summary>
        internal static string L2469 {
            get {
                return ResourceManager.GetString("L2469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأطعمة التي تتناولها ، والإجهاد الذي تشعر به والأنشطة التي تقوم بها كلها تؤثر علي صحتك، والآن يمكنك معرفة كيف كل ذلك ممكن من خلال استكمال تقييمنا الصحي..
        /// </summary>
        internal static string L2470 {
            get {
                return ResourceManager.GetString("L2470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد ضبط كلمة المرور.
        /// </summary>
        internal static string L254 {
            get {
                return ResourceManager.GetString("L254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد الإلكتروني قيد الاستخدام، يرجى تقديم عنوان بريد إلكتروني فريد..
        /// </summary>
        internal static string L2560 {
            get {
                return ResourceManager.GetString("L2560", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لست مؤهلاً لإنشاء حساب ولمزيد من المساعدة يرجى الاتصال بخدمة العملاء على الرقم 1-855-494-1093..
        /// </summary>
        internal static string L2569 {
            get {
                return ResourceManager.GetString("L2569", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية الرابط لإعادة الضبط بعد ساعة واحدة أو سبق استخدامه، يرجى النقر على زر &quot;إعادة ضبط كلمة المرور&quot; وسوف تتلقى رسالة بريد إلكتروني مع رابط جديد..
        /// </summary>
        internal static string L2577 {
            get {
                return ResourceManager.GetString("L2577", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        internal static string L263 {
            get {
                return ResourceManager.GetString("L263", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رحلتك إلى الصحة المثلى والرفاهية تبدأ هنا ... والآن.
        /// </summary>
        internal static string L2693 {
            get {
                return ResourceManager.GetString("L2693", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة نمط حياة الأمومة.
        /// </summary>
        internal static string L2710 {
            get {
                return ResourceManager.GetString("L2710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظف.
        /// </summary>
        internal static string L3070 {
            get {
                return ResourceManager.GetString("L3070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نجحت برامجنا لأكثر من 2 مليون شخص في جميع أنحاء العالم..
        /// </summary>
        internal static string L3111 {
            get {
                return ResourceManager.GetString("L3111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اكسب المكافآت مقابل لجهودك.
        /// </summary>
        internal static string L3112 {
            get {
                return ResourceManager.GetString("L3112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التدريب المباشر.
        /// </summary>
        internal static string L3113 {
            get {
                return ResourceManager.GetString("L3113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العافية وإدارة الحالات الطبية المزمنة.
        /// </summary>
        internal static string L3114 {
            get {
                return ResourceManager.GetString("L3114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرفاه - إدارة الإجهاد - المرونة.
        /// </summary>
        internal static string L3115 {
            get {
                return ResourceManager.GetString("L3115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الإعاقة - العودة إلى العمل.
        /// </summary>
        internal static string L3116 {
            get {
                return ResourceManager.GetString("L3116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقرأ احد قصصنا النجاح المختلفة .
        /// </summary>
        internal static string L3117 {
            get {
                return ResourceManager.GetString("L3117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكنك الفوز بجوائز قيمة من INTERVENT، ويقوم INTERVENT بمنح النقاط مقابل استكمال أنشطة البرامج المختلفة ويجري السحب على أساس شهري والربع والسنوي والنصف السنوي والسنوي لاختيار الفائزين، كلما تجني نقاطا أكثر فتكون فرصتك للفوز أكبر، فقط المشاركون المسجلون والذين يشاركون في برامج التدريب الصحية بفاعلية يتأهلون بدخول السحب..
        /// </summary>
        internal static string L3118 {
            get {
                return ResourceManager.GetString("L3118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابحث عن إعلانات الفائزين وقراءة القصص حول كيف أن العمل مع مدرب صحة INTERVENT يساعد المشاركين على المضي قدما على الطريق إلى الصحة المثلى..
        /// </summary>
        internal static string L3119 {
            get {
                return ResourceManager.GetString("L3119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم الصحي مجاني ، فالتقييم السري عبر الإنترنت الذي يراعي عادات نمط حياتك وتاريخك الصحي لتحديد مدى صحتك وما إذا كنت في خطر يمكنه إدارة بعض الأمراض أو الأمراض المزمنة بشكل أفضل، يستغرق فقط حوالي 15 دقيقة لإكماله..
        /// </summary>
        internal static string L3120 {
            get {
                return ResourceManager.GetString("L3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بمجرد الانتهاء من التقييم الصحي ، سوف تتلقى على الفور تقريرا عن صحتك الشخصية وثروة من المعلومات المفيدة المصممة خصيصًا لك، وعليك إكمال التقييم الصحي قبل القيام بالتسجيل في برنامج التدريب الصحي علي نمط الحياة، يرجى إرسال رسالة بالبريد الإلكتروني أو قم بالاتصال بنا إذا كانت لديك أية أسئلة..
        /// </summary>
        internal static string L3121 {
            get {
                return ResourceManager.GetString("L3121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ويتوافر المدربون الصحيون المتصفون بالرعاية والتفاني في الأوقات التي تناسبك، لقد عملوا مع الآلاف من المشاركين مثلك تمامًا، ويستمع مدربونا إلى احتياجاتك وتفضيلاتك وظروفك ويساعدوك على تطوير خطة فردية لك، وسوف يجعلك المدرب مسؤولاً عن الأهداف التي وضعتها لنفسك ويدعمك في كل خطوة على طريقك نحو صحة أفضل..
        /// </summary>
        internal static string L3122 {
            get {
                return ResourceManager.GetString("L3122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب عليك إكمال التقييم الصحي قبل التسجيل في برنامج التدريب الصحي علي نمط الحياة..
        /// </summary>
        internal static string L3123 {
            get {
                return ResourceManager.GetString("L3123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برامجنا للتدريب الصحي عبر الهاتف تشمل:.
        /// </summary>
        internal static string L3124 {
            get {
                return ResourceManager.GetString("L3124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إن إدارة نمط الحياة - الأكل الصحي ، النشاط البدني ، إدارة الإجهاد ، عدم التدخين واتباع خطتك وتعليماتك العلاجية للرعاية الوقائية - هي الأساس للصحة والرفاهية المثلى.
        /// </summary>
        internal static string L3125 {
            get {
                return ResourceManager.GetString("L3125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وإذا كنت تعيش في حالة مرض مزمنة، فيمكن أن يساعدك برنامجنا الخاص بالتدريب الصحي عبر الهاتف على تنفيذ خطة العلاج التي أوصى بها طبيبك أو مقدم الرعاية الصحية وأن تعيش حياة أفضل مع حالتك الصحية..
        /// </summary>
        internal static string L3126 {
            get {
                return ResourceManager.GetString("L3126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وإذا كنت تتمتع بصحة جيدة بشكل عام وتريد البقاء عليها، سيركز برنامج التدريب على تعزيز الصحة والعافية وإدارة عوامل الخطر والوقاية من الأمراض..
        /// </summary>
        internal static string L3127 {
            get {
                return ResourceManager.GetString("L3127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يتم تخصيص كافة برامج إدارة الحالات الصحية العافية والمزمنة لتلبية احتياجاتك وتفضيلاتك، وسوف تتخذ خطوات صغيرة منتظمة يمكن أن تحدث فرقا كبيرا في صحتك ونمط حياتك..
        /// </summary>
        internal static string L3128 {
            get {
                return ResourceManager.GetString("L3128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عندما التحقت بالدورة التدريبية، علمت أنني أستطيع تقليل خطر الإصابة بداء السكري من خلال التحول إلى مرض السكري من النوع 2 من خلال خسارة ما بين 5 إلى 10 في المائة من وزني وبكوني أكثر نشاطاً بدنياً، وبمساعدة مدربي الصحي فقدت الآن 12 كيلوغراما (حوالي 26 رطلا) ويسعدني ان أقول انني لم أعد مصابا بداء السكري فمعدل الكولسترول  أيضا طبيعي عندي، فإنني أشعر بالارتياح. لما أتمكن من اجراء هذه التغييرات بدون دعم مدربي الصحي، لقد قيّمت برنامج التدريب بأنه ممتاز وأوصي به بالتأكيد للآخرين الذين يحتاجون إلى التعامل مع حالة طبي [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3129 {
            get {
                return ResourceManager.GetString("L3129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإجهاد ليس كله سيئ، ولكن حتى الضغط الجيد، مثل الحصول على ترقية في العمل، يمكن أن يكون مرهقا و يؤثر سلبا على صحتك، وتتناول برامجنا لإدارة الإجهاد مهارات الاسترخاء والتكيف والسلوكيات الهامة الأخرى والتي من شأنها تعزيز المرونة في الأوقات الصعبة. وتشمل المواضيع إدارة الوقت، والتوازن بين العمل والحياة، والقيم، وأساليب وأنماط الاتصال، وبناء الثقة، والدعم الاجتماعي، والوعي، والتفكير بشكل مختلف، وحل المشاكل، والتعامل مع الاكتئاب ومنع الانتكاسات. ويمكن لأي شخص تقريبا الاستفادة من منهجنا الشامل- لكن مخصص على المستوى [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3130 {
            get {
                return ResourceManager.GetString("L3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالنسبة للمشاركين الذين يعانون من مشاكل تتجاوز نطاق برامجنا التدريبية، سنقوم بالإحالة إلى إخصائيي الصحة العقلية المناسبة الآخرين..
        /// </summary>
        internal static string L3131 {
            get {
                return ResourceManager.GetString("L3131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجميع يمر بتجربة التوتر في بعض الوقت - أليس كذلك؟ حسنًا ، بالنسبة لي ، كانت حالة التوتر لدي ناتجة عن فقدان زوجي قبل 25 عامًا. وقد كنت في برنامج تدريب الرفاه لعدة أشهر عندما توفي فجأة، ولحسن الحظ تمكنت من تطبيق العديد من مبادئ المرونة التي تعلمتها من مدربي بشأن التعامل مع الحزن والتوتر لدي. وتمكنت من طلب المساعدة وقبولها والبحث عن الآخرين الذين سيستمعون. كما شاركت في بعض الأنشطة التطوعية في مجتمعي ، مما ساعدني في التركيز على الآخرين بدلاً من التركيز على نفسين وأنا ممتنة لتجربتي التدريبية. هذا البرنامج لديه  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3132 {
            get {
                return ResourceManager.GetString("L3132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تتوقف إدارة نمط الحياة عندما تتعرض لحادث أو تدخل المستشفى أو تصاب بمرض شديد أو نكسات أخرى، وفي الواقع يمكن أن تساعد ممارسة العادات الصحية أثناء هذه الانقطاعات في الحياة على العودة إلى جدولك الزمني الطبيعي والعمل والأنشطة الممتعة في أقرب  وقت ممكن عمليا..
        /// </summary>
        internal static string L3133 {
            get {
                return ResourceManager.GetString("L3133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنساعدك في أن تكون أنت الراعي لصحتك الخاصة لإدارة حالات الإعاقة قصيرة الأجل أو طويلة الأجل، ويمكن أن يساعدك مدربك الصحي الخاص بنمط الحياة على الوصول إلى مجموعة كاملة من موارد الاستعادة، بما في ذلك إعادة التأهيل للمرضى الخارجيين والعلاج الطبيعي. وفي الوقت المناسب يمكنك الانتقال إلى برنامجنا الخاص بإدارة نمط الحياة الشامل  للحصول على الدعم المستمر..
        /// </summary>
        internal static string L3134 {
            get {
                return ResourceManager.GetString("L3134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد العملية الجراحية في الظهر كنت قلقا بشأن العودة إلى العمل، لذا التحقت ببرنامج التدريب بينما كنت في إعادة التأهيل البدني، وخلال هذا الوقت ساعدني المدرب على الوصول إلى خدمات الاستعادة المختلفة والتي كانت ضرورية بالنسبة لي للعودة إلى العمل، وقد ركزنا أيضًا على فقدان الوزن وإدارة ضغط الدم ، وكلاهما كانا يمثلان مشكلتين قبل العملية الجراحية. وبعد أربعة أسابيع فقط تمكنت من العودة إلى العمل على النطاق المحدود وبعد ثلاثة أشهر عدت إلى العمل الشامل. والآن فقدت تسعة كيلوغرامات (حوالي 20 رطلاً)، وتحسن ضغط الدم، وأنا  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3135 {
            get {
                return ResourceManager.GetString("L3135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامج التدريب الصحي على نمط الحياة هذا خاص بالنساء الحوامل  أو اللاتي يخططن للحمل في المستقبل القريب، حيث يركز مواضيع البرنامج المرتبطة بما قبل الولادة بشكل أساسي على الصحة العامة (التغذية والنشاط البدني وإدارة الإجهاد) لدعم الحمل الصحي. وتتناول المواضيع المرتبطة بما بعد الولادة العودة إلى الشكل، وفقدان الوزن الذي اكتسبته أثناء الحمل، والتكيف مع الحياة مع طفل جديد، وتتوفر كذلك سلسلة تعليمية خاصة للنساء اللواتي يفكرن في الرضاعة الطبيعية للطفل..
        /// </summary>
        internal static string L3136 {
            get {
                return ResourceManager.GetString("L3136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يمكن أن تساعد المشاركة في برنامج التدريب الصحي الخاص بنمط حياة الأمهات على تحسين احتمالية الحمل الناجح والطفل السليم، ويتم دائماً إحالة القضايا السريرية إلى أطباء النساء الشخصيين أو مقدمي الرعاية الصحية، كما يتم أيضا تشجيع النساء على الاستفادة من موارد الرعاية المرتبطة بما قبل الولادة والأمومة وحديثي الولادة والتي يقدمها مقدمو الرعاية الصحية حيث يقمن بإنجاب أطفالهن..
        /// </summary>
        internal static string L3137 {
            get {
                return ResourceManager.GetString("L3137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بمجرد علمي بأنني حامل، التحقت ببرنامج تدريب نمط حياة الأمومة، فلم أكن أعرف أي شيء عن ما قد يكون عليه الأمر أن تحمل طفلا، خاصةً المواعيد والاختبارات المرتبطة بما قبل للولادة. قد قام المدرب بالإجابة على على جميع الأسئلة التي طرحتها وساعدني على معرفة ما يمكن توقعه في كل شهر على طول فترة الحمل. وبعد ولادة ابنتي واصلت في برنامج التدريب لإنقاص خمسة كيلوغرامات (حوالي 11 رطل) الإضافية والتي اكتسبتها خلال فترة الحمل وللحصول علي شكل أفضل.  وبعد ثلاثة أشهر فقط عدت إلى وزني الذي كنت عليه قبل الحمل. وأتطلع إلى جلسات الت [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string L3138 {
            get {
                return ResourceManager.GetString("L3138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البوابة التجريبية لعملاء MAXIS GBN.
        /// </summary>
        internal static string L3139 {
            get {
                return ResourceManager.GetString("L3139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        internal static string L3140 {
            get {
                return ResourceManager.GetString("L3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقق الأهداف الهامة بالنسبة لك.
        /// </summary>
        internal static string L3141 {
            get {
                return ResourceManager.GetString("L3141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هاتفنا.
        /// </summary>
        internal static string L3149 {
            get {
                return ResourceManager.GetString("L3149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to راسلنا عبر البريد الإلكتروني.
        /// </summary>
        internal static string L3150 {
            get {
                return ResourceManager.GetString("L3150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العربية-AE.
        /// </summary>
        internal static string L3159 {
            get {
                return ResourceManager.GetString("L3159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERVENT.
        /// </summary>
        internal static string L424 {
            get {
                return ResourceManager.GetString("L424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أفضل صحة من أجل الحياة ™.
        /// </summary>
        internal static string L425 {
            get {
                return ResourceManager.GetString("L425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسجيل الدخول.
        /// </summary>
        internal static string L426 {
            get {
                return ResourceManager.GetString("L426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشاء حساب.
        /// </summary>
        internal static string L431 {
            get {
                return ResourceManager.GetString("L431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإسم الأول مطلوب..
        /// </summary>
        internal static string L432 {
            get {
                return ResourceManager.GetString("L432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير مطلوب..
        /// </summary>
        internal static string L433 {
            get {
                return ResourceManager.GetString("L433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بريدك الإلكتروني مطلوب..
        /// </summary>
        internal static string L434 {
            get {
                return ResourceManager.GetString("L434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير متطابقة.
        /// </summary>
        internal static string L438 {
            get {
                return ResourceManager.GetString("L438", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروط الخدمة.
        /// </summary>
        internal static string L440 {
            get {
                return ResourceManager.GetString("L440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أوافق علي.
        /// </summary>
        internal static string L441 {
            get {
                return ResourceManager.GetString("L441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاستخدام خدماتنا يجب الموافقة على اتفاقية المشاركة والخدمة وسياسة الخصوصية الخاصة بـ INTERVENT ..
        /// </summary>
        internal static string L442 {
            get {
                return ResourceManager.GetString("L442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        internal static string L443 {
            get {
                return ResourceManager.GetString("L443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احصل على تقريرمخصص للصحة والعافية .
        /// </summary>
        internal static string L446 {
            get {
                return ResourceManager.GetString("L446", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقق الأهداف المهمة بالنسبة لك.
        /// </summary>
        internal static string L451 {
            get {
                return ResourceManager.GetString("L451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعامل مع مدرب الصحة.
        /// </summary>
        internal static string L453 {
            get {
                return ResourceManager.GetString("L453", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل إلى INTERVENT أثناء التنقل.
        /// </summary>
        internal static string L459 {
            get {
                return ResourceManager.GetString("L459", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد تم تأكيد حسابك الجديد! استخدم عنوان البريد الإلكتروني وكلمة المرور لتسجيل الدخول..
        /// </summary>
        internal static string L462 {
            get {
                return ResourceManager.GetString("L462", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال عنوان بريدك الإلكتروني.
        /// </summary>
        internal static string L463 {
            get {
                return ResourceManager.GetString("L463", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إدخال كلمة المرور الخاصة بك.
        /// </summary>
        internal static string L464 {
            get {
                return ResourceManager.GetString("L464", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور.
        /// </summary>
        internal static string L465 {
            get {
                return ResourceManager.GetString("L465", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمه المرور.
        /// </summary>
        internal static string L466 {
            get {
                return ResourceManager.GetString("L466", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} غير موجود في نظامنا، يرجى الاتصال بنا على 1-855-494-1093 لمزيد من المساعدة..
        /// </summary>
        internal static string L467 {
            get {
                return ResourceManager.GetString("L467", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من بريدك الإلكتروني للحصول على الإرشادات المتعلقة بإعادة ضبط كلمة المرور..
        /// </summary>
        internal static string L468 {
            get {
                return ResourceManager.GetString("L468", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنرسل لك التعليمات عبر البريد الإلكتروني حول كيفية إعادة ضبط كلمة المرور الخاصة بك..
        /// </summary>
        internal static string L469 {
            get {
                return ResourceManager.GetString("L469", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أعد ضبط كلمة المرور.
        /// </summary>
        internal static string L470 {
            get {
                return ResourceManager.GetString("L470", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الحساب.
        /// </summary>
        internal static string L474 {
            get {
                return ResourceManager.GetString("L474", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رسالة تأكيد بالبريد الإلكتروني إلى.
        /// </summary>
        internal static string L475 {
            get {
                return ResourceManager.GetString("L475", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انقر فوق الرابط الموجود في الرسالة للتحقق من صحة واستكمال عملية إنشاء حسابك..
        /// </summary>
        internal static string L476 {
            get {
                return ResourceManager.GetString("L476", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إذا لم تتمكن من العثور عليه في البريد الوارد ، فحاول البحث في مجلد الرسائل غير المرغوب فيها..
        /// </summary>
        internal static string L477 {
            get {
                return ResourceManager.GetString("L477", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسنا.
        /// </summary>
        internal static string L478 {
            get {
                return ResourceManager.GetString("L478", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطا اثناء عملية طلب التحقق من صحة الحساب..
        /// </summary>
        internal static string L479 {
            get {
                return ResourceManager.GetString("L479", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التقييم الصحي.
        /// </summary>
        internal static string L535 {
            get {
                return ResourceManager.GetString("L535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الاول.
        /// </summary>
        internal static string L938 {
            get {
                return ResourceManager.GetString("L938", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير.
        /// </summary>
        internal static string L939 {
            get {
                return ResourceManager.GetString("L939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان البريد الكتروني.
        /// </summary>
        internal static string L986 {
            get {
                return ResourceManager.GetString("L986", resourceCulture);
            }
        }
    }
}
